apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: khipster
type: Opaque
data:
  secret: WWpnM1pqZzNZall3TldRd01URTNZbVpsTm1aaFltRTRZVGxrWVdVeU1ESTFNVEl5T0RJd01UazVPR0pqWWpneU16VTNOMkZpTkRCaFlXSXhOV1JoTVdZMk1USm1Zek14TkRrNE4yTXlaV1l4T0dJeU1qUTVaVEUxTWpjM1pHSXdaamM1TkE9PQ==
